version: '3.9'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/uefa
      APP_PORT: 8081
      DATASOURCE_URL: jdbc:postgresql://localhost:5432/uefa
      DATASOURCE_USER: root
      DATASOURCE_PASSWORD: root
    ports:
      - "8081:8081"
    networks:
      - backend

  db:
    container_name: db
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: uefa
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  backend:
    name: app-network

volumes:
  db-data: